/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AmSideDrawer {
        "open": () => Promise<void>;
        "opened": boolean;
        "title": string;
    }
    interface AmTooltip {
        "text": string;
    }
}
declare global {
    interface HTMLAmSideDrawerElement extends Components.AmSideDrawer, HTMLStencilElement {
    }
    var HTMLAmSideDrawerElement: {
        prototype: HTMLAmSideDrawerElement;
        new (): HTMLAmSideDrawerElement;
    };
    interface HTMLAmTooltipElement extends Components.AmTooltip, HTMLStencilElement {
    }
    var HTMLAmTooltipElement: {
        prototype: HTMLAmTooltipElement;
        new (): HTMLAmTooltipElement;
    };
    interface HTMLElementTagNameMap {
        "am-side-drawer": HTMLAmSideDrawerElement;
        "am-tooltip": HTMLAmTooltipElement;
    }
}
declare namespace LocalJSX {
    interface AmSideDrawer {
        "opened"?: boolean;
        "title"?: string;
    }
    interface AmTooltip {
        "text"?: string;
    }
    interface IntrinsicElements {
        "am-side-drawer": AmSideDrawer;
        "am-tooltip": AmTooltip;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "am-side-drawer": LocalJSX.AmSideDrawer & JSXBase.HTMLAttributes<HTMLAmSideDrawerElement>;
            "am-tooltip": LocalJSX.AmTooltip & JSXBase.HTMLAttributes<HTMLAmTooltipElement>;
        }
    }
}
